import { z } from "zod";

export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/jpg", "image/png"];
export const ACCEPTED_DOC_TYPES = ["application/pdf", "image/jpeg", "image/jpg"];

export const fileSchema = z
  .any()
  .refine((file) => !file || file.size <= MAX_FILE_SIZE, "Max file size is 5MB.")
  .refine(
    (file) => !file || ACCEPTED_DOC_TYPES.includes(file.type),
    "Only .pdf and .jpg formats are supported."
  );

export const imageFileSchema = z
  .any()
  .refine((file) => !file || file.size <= MAX_FILE_SIZE, "Max file size is 5MB.")
  .refine(
    (file) => !file || ACCEPTED_IMAGE_TYPES.includes(file.type),
    "Only .jpg, .jpeg, and .png formats are supported."
  );

// Helper to convert date strings to Date objects
const dateStringToDate = z
  .string()
  .min(1, "Date is required.")
  .refine((val) => !isNaN(Date.parse(val)), "Invalid date format.")
  .transform((val) => new Date(val));

export const visaApplicationSchema = z.object({
  fullName: z.string().min(1, "Full name is required."),
  gender: z.string().min(1, "Gender is required."),
  dateOfBirth: dateStringToDate,
  placeOfBirth: z.string().min(1, "Place of birth is required."),
  nationality: z.string().min(1, "Nationality is required."),
  maritalStatus: z.string().min(1, "Marital status is required."),
  religion: z.string().min(1, "Religion is required."),
  occupation: z.string().min(1, "Occupation is required."),
  education: z.string().min(1, "Education qualification is required."),
  fatherName: z.string().min(1, "Father's name is required."),
  motherName: z.string().min(1, "Mother's name is required."),
  passportNumber: z.string().min(1, "Passport number is required."),
  passportIssuePlace: z.string().min(1, "Place of issue is required."),
  passportIssueDate: dateStringToDate,
  passportExpiryDate: dateStringToDate,
  passportType: z.string().min(1, "Passport type is required."),
  passportCopy: fileSchema,
  isResident: z.boolean().default(false),
  residenceCountry: z.string().optional(),
  residentId: z.string().optional(),
  residentIdIssueDate: dateStringToDate.optional(),
  residentIdExpiryDate: dateStringToDate.optional(),
  residentIdCopy: z.any().optional(),
  mobileNumber: z.string().min(1, "Mobile number is required."),
  email: z.string().email("Invalid email address."),
  permanentAddress: z.string().min(1, "Permanent address is required."),
  currentAddress: z.string().optional(),
  visitPurpose: z.string().min(1, "Purpose of visit is required."),
  visaType: z.string().min(1, "Type of visa is required."),
  stayDuration: z.string().min(1, "Duration of stay is required."),
  entryDate: dateStringToDate,
  portOfEntry: z.string().min(1, "Port of entry is required."),
  hostDetails: z.string().optional(),
  companyName: z.string().min(1, "Company name is required."),
  jobTitle: z.string().min(1, "Job title is required."),
  workAddress: z.string().min(1, "Work address is required."),
  workContact: z.string().min(1, "Work contact number is required."),
  noc: fileSchema,
  salaryCertificate: z.any().optional(),
  bankStatement: fileSchema,
  companyBankStatement: z.any().optional(),
  proofOfIncome: z.any().optional(),
  photo: imageFileSchema,
  travelInsurance: fileSchema,
  flightBooking: fileSchema,
  hotelBooking: fileSchema,
  invitationLetter: z.any().optional(),
  tradeLicense: z.any().optional(),
  destinationCountry: z.string().optional(),
  travelPurpose: z.string().optional(),
  travelStartDate: dateStringToDate.optional(),
  travelEndDate: dateStringToDate.optional(),
  accommodationDetails: z.string().optional(),
  employmentStatus: z.string().optional(),
  employerName: z.string().optional(),
  employerAddress: z.string().optional(),
  employerContact: z.string().optional(),
  employmentProof: z.any().optional(),
  financialProof: z.any().optional(),
  returnTicket: z.any().optional(),
  additionalDocuments: z.any().optional(),
  emergencyContactName: z.string().optional(),
  emergencyContactRelation: z.string().optional(),
  emergencyContactPhone: z.string().optional(),
  phoneNumber: z.string().optional(),
  countryOfResidence: z.string().optional(),
  residencePermitNumber: z.string().optional(),
  residencePermitExpiry: dateStringToDate.optional(),
  residencyProof: z.any().optional(),
});
export const countryMap = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo (Brazzaville)",
  CD: "Congo (Kinshasa)",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Côte d’Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czechia",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Vatican City",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MK: "North Macedonia",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn Islands",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  BL: "Saint Barthélemy",
  SH: "Saint Helena",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "São Tomé and Príncipe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe"
};